from fastapi import APIRouter, HTTPException
from schemas.prediction import PredictionRequest, PredictionResponse, ChatRequest, ChatResponse
from ml.model import predictor

router = APIRouter(prefix="/api", tags=["API"])

@router.post("/predict", response_model=PredictionResponse)
async def predict_hallucination(request: PredictionRequest):
    """
    Endpoint to predict hallucinations in a given text generated by an LLM.
    """
    try:
        prediction_result = predictor.predict(text=request.text, domain=request.domain)
        return PredictionResponse(**prediction_result)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/chat", response_model=ChatResponse)
async def chat_with_model(request: ChatRequest):
    """
    Endpoint to generate a response from the LLM.
    """
    try:
        messages = [{"role": msg.role, "content": msg.content} for msg in request.messages]
        response_text = predictor.chat(messages=messages, model_name=request.model_name)
        return ChatResponse(response=response_text)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
